// Generated by CoffeeScript 1.6.3
var data, lumber;

lumber = require("./index");

lumber.timer("hi");

lumber.h1("fun");

lumber.h2("fun");

lumber.h3("fun");

lumber.red("howdy");

lumber.blue("howdy");

lumber.green("howdy");

lumber.yellow("howdy");

lumber.since("hi");

data = [
  {
    g: [2, 3],
    e: 2
  }, {
    f: "fn"
  }
];

lumber.inspect(data);
